name: Push CI

on:
  push:
    branches: main

permissions:
  contents: read

concurrency:
  group: push-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/ci-reusable.yml
    with:
      checkout_ref: ${{ github.sha }}
      checkout_repository: ${{ github.repository }}
